# Generated by Django 2.0.1 on 2018-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_headline', models.CharField(max_length=100)),
            ],
        ),
    ]
